"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-04-10
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("users", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("email", sa.String(255), nullable=False), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("role", sa.Enum("admin","agent","manager", name="user_role"), nullable=False), sa.Column("calendar_connected", sa.Boolean(), nullable=False, server_default=sa.text("false")), sa.Column("calendar_token", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table("companies", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("website", sa.String(255)), sa.Column("industry", sa.String(255)), sa.Column("arr_range", sa.String(100)), sa.Column("employee_count", sa.Integer()), sa.Column("funding_stage", sa.String(100)), sa.Column("tam_estimate", sa.String(100)), sa.Column("tech_stack", sa.JSON()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))

    op.create_table("contacts", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False), sa.Column("first_name", sa.String(100), nullable=False), sa.Column("last_name", sa.String(100), nullable=False), sa.Column("email", sa.String(255)), sa.Column("phone", sa.String(50)), sa.Column("linkedin_url", sa.String(255)), sa.Column("job_title", sa.String(255)), sa.Column("seniority", sa.Enum("c_suite","vp","director","manager","ic", name="seniority")), sa.Column("is_verified", sa.Boolean(), nullable=False, server_default=sa.text("false")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))

    op.create_table("campaigns", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False), sa.Column("target_segment", sa.Text()), sa.Column("status", sa.Enum("draft","active","paused","completed", name="campaign_status"), nullable=False), sa.Column("channels", sa.JSON()), sa.Column("total_prospects", sa.Integer(), nullable=False, server_default="0"), sa.Column("start_date", sa.DateTime(timezone=True)), sa.Column("end_date", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))

    op.create_table("prospects", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False), sa.Column("contact_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("contacts.id"), nullable=False), sa.Column("icp_score", sa.Integer()), sa.Column("status", sa.Enum("new","researched","contacted","meeting_booked","nurture","disqualified", name="prospect_status"), nullable=False), sa.Column("assigned_to", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id")), sa.Column("campaign_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("campaigns.id")), sa.Column("pain_points", sa.JSON()), sa.Column("buying_signals", sa.JSON()), sa.Column("preferred_channel", sa.Enum("call","email","linkedin", name="preferred_channel")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))

    op.create_table("call_scripts", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("campaign_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("campaigns.id")), sa.Column("prospect_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("prospects.id")), sa.Column("is_template", sa.Boolean(), nullable=False, server_default=sa.text("false")), sa.Column("opening", sa.Text()), sa.Column("value_prop", sa.Text()), sa.Column("objection_handling", sa.JSON()), sa.Column("close", sa.Text()), sa.Column("version", sa.Integer(), nullable=False, server_default="1"), sa.Column("created_by", sa.Enum("ai","human", name="created_by"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))

    op.create_table("calls", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("prospect_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("prospects.id"), nullable=False), sa.Column("campaign_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("campaigns.id")), sa.Column("agent_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False), sa.Column("script_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("call_scripts.id"), nullable=False), sa.Column("status", sa.Enum("initiated","connected","voicemail","no_answer","completed","failed", name="call_status"), nullable=False), sa.Column("outcome", sa.Enum("meeting_booked","follow_up","not_interested","wrong_contact","callback", name="call_outcome")), sa.Column("duration_seconds", sa.Integer()), sa.Column("recording_url", sa.String(500)), sa.Column("transcript", sa.Text()), sa.Column("ai_summary", sa.Text()), sa.Column("sentiment", sa.Enum("positive","neutral","negative", name="sentiment")), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("ended_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))

    op.create_table("call_objections", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("call_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("calls.id"), nullable=False), sa.Column("objection_type", sa.String(255), nullable=False), sa.Column("response_used", sa.Text()), sa.Column("was_successful", sa.Boolean(), nullable=False, server_default=sa.text("false")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))

    op.create_table("emails", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("prospect_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("prospects.id"), nullable=False), sa.Column("campaign_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("campaigns.id")), sa.Column("sequence_step", sa.Integer()), sa.Column("subject", sa.String(255)), sa.Column("body", sa.Text()), sa.Column("status", sa.Enum("draft","sent","opened","clicked","replied","bounced", name="email_status"), nullable=False), sa.Column("opened_at", sa.DateTime(timezone=True)), sa.Column("clicked_at", sa.DateTime(timezone=True)), sa.Column("replied_at", sa.DateTime(timezone=True)), sa.Column("sent_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))

    op.create_table("linkedin_messages", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("prospect_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("prospects.id"), nullable=False), sa.Column("campaign_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("campaigns.id")), sa.Column("message_type", sa.Enum("connection_request","warm_message","follow_up", name="message_type"), nullable=False), sa.Column("content", sa.Text()), sa.Column("status", sa.Enum("sent","accepted","replied", name="linkedin_status"), nullable=False), sa.Column("sent_at", sa.DateTime(timezone=True)), sa.Column("replied_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))

    op.create_table("follow_up_sequences", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("prospect_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("prospects.id"), nullable=False), sa.Column("campaign_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("campaigns.id")), sa.Column("sequence_type", sa.Enum("short_term","nurture","re_engagement", name="sequence_type"), nullable=False), sa.Column("current_step", sa.Integer(), nullable=False, server_default="1"), sa.Column("total_steps", sa.Integer(), nullable=False, server_default="1"), sa.Column("next_touchpoint_at", sa.DateTime(timezone=True)), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))

    op.create_table("meetings", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("prospect_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("prospects.id"), nullable=False), sa.Column("call_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("calls.id")), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False), sa.Column("title", sa.String(255)), sa.Column("scheduled_at", sa.DateTime(timezone=True)), sa.Column("duration_minutes", sa.Integer()), sa.Column("calendar_event_id", sa.String(255)), sa.Column("meet_link", sa.String(500)), sa.Column("status", sa.Enum("scheduled","confirmed","completed","cancelled","no_show", name="meeting_status"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))

    op.create_table("crm_connections", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False), sa.Column("crm_type", sa.Enum("hubspot","salesforce","pipedrive", name="crm_type"), nullable=False), sa.Column("access_token", sa.Text()), sa.Column("refresh_token", sa.Text()), sa.Column("last_synced_at", sa.DateTime(timezone=True)), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))

    op.create_table("touchpoint_log", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("prospect_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("prospects.id"), nullable=False), sa.Column("touchpoint_type", sa.Enum("call","email","linkedin","meeting", name="touchpoint_type"), nullable=False), sa.Column("reference_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("outcome_summary", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))

    op.create_table("re_engagement_triggers", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("prospect_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("prospects.id"), nullable=False), sa.Column("trigger_type", sa.Enum("website_visit","linkedin_activity","funding_round","job_post", name="trigger_type"), nullable=False), sa.Column("detected_at", sa.DateTime(timezone=True)), sa.Column("action_taken", sa.Text()), sa.Column("was_actioned", sa.Boolean(), nullable=False, server_default=sa.text("false")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))

    op.create_table("async_jobs", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("job_type", sa.String(120), nullable=False), sa.Column("resource_type", sa.String(120)), sa.Column("resource_id", postgresql.UUID(as_uuid=True)), sa.Column("status", sa.Enum("queued","running","completed","failed", name="job_status"), nullable=False), sa.Column("payload", sa.JSON()), sa.Column("result", sa.JSON()), sa.Column("error_message", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))


def downgrade() -> None:
    for table in ["async_jobs","re_engagement_triggers","touchpoint_log","crm_connections","meetings","follow_up_sequences","linkedin_messages","emails","call_objections","calls","call_scripts","prospects","campaigns","contacts","companies","users"]:
        op.drop_table(table)
